### ISSUE TITLE
Tried to sync a weather station without success - Help Wanted

### ISSUE THREAD

**Issue by HoracioDos** [hzeller/txtempus#6]
Hello!
I tried to sync a DCF77 weather station without success. I have a raspberry model B and this what I get when I execute txtempus. I attached txmodulation file and hardware setup image.
```
sudo txtempus -v  -s DCF77
Requesting 77500 Hz, getting 77500.003 Hz carrier
2019-05-31 19:36:59
2019-05-31 19:37:59
2019-05-31 19:38:59
2019-05-31 19:39:44
```
How can I know if it is doing something?
![DCF77_Hardware](https://user-images.githubusercontent.com/4549674/58738986-762ab700-83de-11e9-9b20-114b8e9ca917.jpg)
[TXModulation.txt](https://github.com/hzeller/txtempus/files/3243090/TXModulation.txt)

**Comment by electrogoodie** [comment]
I used a LAN Cable, UTP Cat 5e,  and stripped any of the eight wires (AWG #23 I guess). Made a 10-inch (25.4cm) diameter coil with 25 turns (if you want you can google for an online inductance calculator and use an LCR tester to obtain the correct diameter of the loop and the no. of turns for 77.5kHz). Kindly check if your RBPi is made in China (RS Components) or made in UK (element14). My RBPi Zero WH from RS did not work too but when I changed to a Pi purchased from element14, everything worked well.

**Comment by hzeller** [comment]
I'd probably make the antenna a little more wire: take  a meter or so and make a coil out of it. Also, you want to align the coil so that its axis is aligned with the ferrite axis inside your weather station. Antennas are not very sensitive and for some you need to get pretty close before they pick up things.

To know if it does something, ideally you can measure the output with an oscilloscope; or some multimeters also have a frequency measure mode which you can use.

There was one report in #1 where the generated frequency was wrong for unknown reason. Have a look at the solution exploration there if that is indeed the problem.

**Comment by HoracioDos** [comment]
Good to know! Thanks! I'll borrow a DSO today to measure freq in GPIO4 output as it was commented in other issue. In the meanwhile I'll try to reproduce your coil/antenna. Do you have some pic of it?
Thanks again!

**Comment by HoracioDos** [comment]
Hello @hzeller  Thanks for your advice. I'll try to follow all your comments and I'll report back

**Comment by electrogoodie** [comment]
¡Hola! @HoracioDos 
![20190602_105848](https://user-images.githubusercontent.com/45380265/58756242-d7f63880-8526-11e9-96ab-24defde6215e.jpg)

**Comment by HoracioDos** [comment]
Hello! This is getting better. Frequency is Ok in a raspberry pi model B. There is no need to change something in software, so I need to improve the coil/antenna.
Thanks to everyone! ![DS1Z_QuickPrint1](https://user-images.githubusercontent.com/4549674/58763197-3a066c00-852e-11e9-95ff-8a8a07d7da60.png)
